# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dev' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dev

pod 'NMapsMap'

end

target 'Release' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Release

pod 'NMapsMap'

end
